Problem Statement:

You are a database administrator. You want to use the data to answer a few
questions about your customers, especially about the sales and profit coming
from different states, money spent in marketing and various other factors such as
COGS (Cost of Goods Sold), budget profit etc. You plan on using these insights
to help find out which items are being sold the most. You have been provided
with the sample of the overall customer data due to privacy issues. But you hope
that these samples are enough for you to write fully functioning SQL queries to
help answer the questions.

SELECT * FROM Fact
SELECT * FROM Location
SELECT * FROM Product

1.Display the number of states present in the LocationTable.

SELECT COUNT(DISTINCT State) AS NoOfState FROM Location

2. How many products are of regular type?

SELECT COUNT(DISTINCT Product) AS NoOfProduct FROM Product
WHERE Type='Regular'

3. How much spending has been done on marketing of product ID 1?

SELECT SUM(MArketing) AS TotalMArketingExpense FROM FACT
WHERE ProductId=1


4. What is the minimum sales of a product?

SELECT MIN(Sales) AS MinSalesValue FROM FACT


5. Display the max Cost of Good Sold (COGS).

SELECT MAX(COGS) AS MAX_COGS FROM FACT


6. Display the details of the product where product type is coffee.

SELECT * FROM Product WHERE Product_Type='Coffee'


7. Display the details where total expenses are greater than 40.

SELECT * FROM FACT AS F
INNER JOIN Product AS P ON F.ProductId=P.ProductId
WHERE Total_Expenses>40

8. What is the average sales in area code 719?

SELECT AVG(Sales) AS AverageSales FROM Fact
WHERE Area_Code=719

9. Find out the total profit generated by Colorado state.

SELECT SUM(Profit) AS TotalProfit FROM FACT AS F
JOIN Location AS L ON F.Area_Code=L.Area_Code
WHERE State='Colorado'


10. Display the average inventory for each product ID.

SELECT ProductId, AVG(Inventory) AS AvgInventory FROM Fact
GROUP BY ProductId
ORDER BY ProductId

11. Display state in a sequential order in a Location Table.

SELECT DISTINCT STATE FROM Location
ORDER BY State


12. Display the average budget of the area code where the average budget
margin should be greater than 100.

SELECT Area_Code, AVG(Budget_Margin) AS AvgBudgetMargin FROM Fact
GROUP BY Area_Code
HAVING AVG(Budget_Margin) > 100


13. What is the total sales done on date 2010-01-01?

SELECT SUM(Sales) AS TotalSales FROM Fact
WHERE DATE = '2010-01-01'


14. Display the average total expense of each product ID on an individual date.

SELECT Date, ProductId, AVG(Total_Expenses) AS AvgExpenses
FROM Fact
GROUP BY Date, ProductId
ORDER BY Date, ProductId


15. Display the table with the following attributes such as date, productID,
product_type, product, sales, profit, state, area_code.

SELECT F.Date, P.*, F.Sales, F.Profit, L.State, L.Area_Code
FROM Fact AS F
JOIN Location AS L ON F.Area_Code= L.Area_Code
JOIN Product AS P ON F.ProductId=P.ProductId


16. Display the rank without any gap to show the sales wise rank.

SELECT Sales, DENSE_RANK() 
OVER (ORDER BY Sales DESC) AS DRank FROM FACT


17. Find the state wise profit and sales.

SELECT L.State, SUM(F.Profit) AS TotalProfit, SUM(F.Sales) AS TotalSales FROM Fact AS F
JOIN Location AS L ON F.Area_Code= L.Area_Code
GROUP BY L.State


18. Find the state wise profit and sales along with the product name.


SELECT L.State, P.Product, SUM(F.Profit) AS TotalProfit, SUM(F.Sales) AS TotalSales FROM Fact AS F
JOIN Location AS L ON F.Area_Code= L.Area_Code
JOIN Product AS P ON F.ProductId=P.ProductId
GROUP BY L.State, P.Product

19. If there is an increase in sales of 5%, calculate the increasedsales.

SELECT Sales, (Sales*1.05) AS IncSales
FROM Fact


20. Find the maximum profit along with the product ID and producttype.

SELECT P.ProductId, P.Product_Type, MAX(F.Profit) AS MaxProfit FROM Fact AS F
JOIN Product AS P ON F.ProductId=P.ProductId
GROUP BY P.ProductId, P.Product_Type


21. Create a stored procedure to fetch the result according to the product type
from Product Table.

CREATE PROCEDURE usp_Product_Type 
(
@ProductType VARCHAR(50) 
)
AS BEGIN
SELECT * FROM Product WHERE Product_Type=@ProductType
END

EXEC usp_Product_Type 'coffee'

EXEC usp_Product_Type 'tea'


22. Write a query by creating a condition in which if the total expenses is less than
60 then it is a profit or else loss.

SELECT Total_Expenses,
IIF(Total_Expenses<60,'Profit','Loss') AS Status
FROM Fact

23. Give the total weekly sales value with the date and product ID details. Use
roll-up to pull the data in hierarchical order.

SELECT DATEPART(Week,Date) AS Week, ProductId, SUM(Sales) AS TotalSales FROM FACT
GROUP BY DATEPART(Week,Date), ProductId WITH ROLLUP
ORDER BY DATEPART(Week,Date), ProductId


24. Apply union and intersection operator on the tables which consist of
attribute area code.

SELECT Area_Code FROM Fact
UNION
SELECT Area_Code FROM Location

SELECT Area_Code FROM Fact
INTERSECT
SELECT Area_Code FROM Location


25. Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference.

SELECT * FROM Product
CREATE FUNCTION udf_ProductType
(
@ProductType VARCHAR(50)
)
RETURNS TABLE
RETURN
(SELECT * FROM Product WHERE Product_Type=@ProductType)

SELECT * FROM udf_ProductType('Coffee')


26. Change the product type from coffee to tea where product ID is 1 and undo
it.

BEGIN TRANSACTION
UPDATE Product
SET Product_Type='Tea'
WHERE ProductId=1

ROLLBACK
 
SELECT * FROM Product

27. Display the date, product ID and sales where total expenses are
between 100 to 200.

SELECT Date, ProductId, Sales FROM Fact
WHERE Total_Expenses BETWEEN 100 AND 200

28. Delete the records in the Product Table for regular type.

BEGIN TRANSACTION
DELETE FROM Product WHERE Type='Regular'

ROLLBACK

SELECT * FROM Product

29. Display the ASCII value of the fifth character from the columnProduct.

SELECT Product, SUBSTRING(Product,5,1) AS Character,
ASCII(SUBSTRING(Product,5,1)) AS ASCII
FROM Product


